<a href="https://colab.research.google.com/github/MarcinJanCiesielski/data_science_bootcamp/blob/main/01_wprowadzenie/02_algebra_liniowa.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Norma wektorowa, długość wektora w R2

In [1]:
import numpy as np
np.__version__

'1.21.6'

In [ ]:
v1 = np.array([0, 4])
v1

array([0, 4])

In [ ]:
np.linalg.norm(v1)  # norma wektorowa (długość wektora)

4.0

In [ ]:
v2 = np.array([-10, 10, 13])

In [ ]:
np.linalg.norm(v2)

19.209372712298546

In [ ]:
p = np.array([3, 0])

In [ ]:
q = np.array([0,4])

In [ ]:
np.linalg.norm(p - q)

5.0

In [ ]:
p = np.array([3, 0, 1])
q = np.array([0, 4, 2])
np.linalg.norm(p - q)

5.0990195135927845

In [ ]:
x = np.array([[5, 3], [3, 9]])
y = np.array([[1], [-1]])
print(x, '\n')
print(y)

[[5 3]
 [3 9]] 

[[ 1]
 [-1]]


In [ ]:
z = np.dot(x, y)
z

array([[ 2],
       [-6]])

In [ ]:
z.shape

(2, 1)

In [ ]:
X = np.array([[2, -1, 3],
              [3, 1, 0]])
Y = np.array([[2, 1, -1],
              [0, -1, 2],
              [3, 2, 0]])

print(X, '\n')
print(Y)

[[ 2 -1  3]
 [ 3  1  0]] 

[[ 2  1 -1]
 [ 0 -1  2]
 [ 3  2  0]]


In [ ]:
z = np.dot(X, Y)
z

array([[13,  9, -4],
       [ 6,  2, -1]])

# Wyznacznik macierzy

In [4]:
a = np.array([[2, 4], [-1, 3]])
round(np.linalg.det(a))

10

In [5]:
np.trace(a)  # ślad macierzy - suma elementó na przekąnej

5

In [7]:
np.eye(5, dtype=int)  # generuje macierz jednostkową czyli kwadratową, gdze na przekątnej są tylko 1-ki

array([[1, 0, 0, 0, 0],
       [0, 1, 0, 0, 0],
       [0, 0, 1, 0, 0],
       [0, 0, 0, 1, 0],
       [0, 0, 0, 0, 1]])

In [10]:
a = np.array([[2, 4], [-1, 3]])
b = np.linalg.inv(a)  # generuje macierz odwrotną do a czyli taka, że po przmnożeniu przez a da macierz jednostkową
np.set_printoptions(precision=4, suppress=True)
np.dot(a,b)

array([[1., 0.],
       [0., 1.]])

In [11]:
np.dot(b,a)

array([[ 1., -0.],
       [ 0.,  1.]])

In [12]:
np.transpose(a)  # transponowanie macierzy - zamiana wierszy z kolumnmi

array([[ 2, -1],
       [ 4,  3]])

In [14]:
a.T  # to samo co transpose

array([[ 2, -1],
       [ 4,  3]])

# Rozwiązywanie układów równań

In [16]:
a = np.array([[2, 4],[1, -1]])
a

array([[ 2,  4],
       [ 1, -1]])

In [18]:
b = np.array([[10], [-1]])
b

array([[10],
       [-1]])

In [19]:
a_inv = np.linalg.inv(a)
a_inv

array([[ 0.1667,  0.6667],
       [ 0.1667, -0.3333]])

In [20]:
x = np.dot(a_inv, b)
x  # równania rozwiązane

array([[1.],
       [2.]])