<a href="https://colab.research.google.com/github/MarcinJanCiesielski/data_science_bootcamp/blob/main/01_Wprowadzenie%5C01_numpy_intro.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import numpy as np
np.__version__


'1.21.6'

In [ ]:
dir(np)

In [ ]:
help(np.array)

In [ ]:
x = np.array([1, 3])

In [ ]:
print(x)

[1 3]


In [ ]:
type(x)

numpy.ndarray

In [ ]:
x.ndim

1

In [ ]:
x.shape

(2,)

In [ ]:
x.size

2

In [ ]:
x.dtype

dtype('int64')

In [ ]:
x = np.array([1.3, 2.3, 1.4])

In [ ]:
print(x)

[1.3 2.3 1.4]


In [ ]:
x.dtype

dtype('float64')

In [ ]:
x = np.array([[1, 2], [-3, 1]])

In [ ]:
x.ndim

2

In [ ]:
x.shape

(2, 2)

In [ ]:
x = np.array([[1, 2, 3], [4, 2, 1]])

In [ ]:
x.shape

(2, 3)

In [ ]:
x = np.array(
    [[[4, 3, 1],
      [3, 1, 2]],
     
     [[4, 1, 3],
      [4, 2, 1]],
     
     [[3, 2, 1],
      [4, 3, 2]]]
)
x

array([[[4, 3, 1],
        [3, 1, 2]],

       [[4, 1, 3],
        [4, 2, 1]],

       [[3, 2, 1],
        [4, 3, 2]]])

In [ ]:
x.ndim

3

In [ ]:
x.shape

(3, 2, 3)

In [ ]:
a = np.array([1, 2, 3])
a.dtype

dtype('int64')

In [ ]:
a = np.array([1.0, 2.3, 3.3])
a.dtype

dtype('float64')

In [ ]:
a = np.array([1, 2, 3], dtype='float')
a.dtype

dtype('float64')

In [ ]:
a = np.array([1, 2, 3], dtype='complex')
a.dtype

dtype('complex128')

In [ ]:
a = np.array([1.0, 2.3, 3.3], dtype='int')
a.dtype

dtype('int64')

In [ ]:
a

array([1, 2, 3])

In [ ]:
a = np.array([True, False])
a.dtype

dtype('bool')

In [ ]:
a = np.array([24, 120, 230], dtype=np.int8)
a.dtype

dtype('int8')

In [ ]:
a = np.array([24, 120, 230], dtype=np.uint8)
a.dtype

dtype('uint8')

Tworzenie tablic

In [ ]:
a = np.zeros(shape=(4, 10))
a

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [ ]:
a = np.zeros(shape=(4, 10), dtype='int')
a

array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0]])

In [ ]:
np.ones(shape=(5, 5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [ ]:
np.ones(shape=(5, 5), dtype='int')

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [ ]:
np.full(shape=(3, 3), fill_value=4, dtype='int')

array([[4, 4, 4],
       [4, 4, 4],
       [4, 4, 4]])

In [ ]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
list(range(10))

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [ ]:
np. arange(start=5, stop=10)

array([5, 6, 7, 8, 9])

In [ ]:
np.arange(start=10, stop=100, step=10)

array([10, 20, 30, 40, 50, 60, 70, 80, 90])

In [ ]:
np.arange(start=100, stop=10, step=-10)

array([100,  90,  80,  70,  60,  50,  40,  30,  20])

In [ ]:
np.arange(start=0, stop=1, step=0.05)

array([0.  , 0.05, 0.1 , 0.15, 0.2 , 0.25, 0.3 , 0.35, 0.4 , 0.45, 0.5 ,
       0.55, 0.6 , 0.65, 0.7 , 0.75, 0.8 , 0.85, 0.9 , 0.95])

In [ ]:
np.linspace(start=0, stop=1, num=110)

array([0.        , 0.00917431, 0.01834862, 0.02752294, 0.03669725,
       0.04587156, 0.05504587, 0.06422018, 0.0733945 , 0.08256881,
       0.09174312, 0.10091743, 0.11009174, 0.11926606, 0.12844037,
       0.13761468, 0.14678899, 0.1559633 , 0.16513761, 0.17431193,
       0.18348624, 0.19266055, 0.20183486, 0.21100917, 0.22018349,
       0.2293578 , 0.23853211, 0.24770642, 0.25688073, 0.26605505,
       0.27522936, 0.28440367, 0.29357798, 0.30275229, 0.31192661,
       0.32110092, 0.33027523, 0.33944954, 0.34862385, 0.35779817,
       0.36697248, 0.37614679, 0.3853211 , 0.39449541, 0.40366972,
       0.41284404, 0.42201835, 0.43119266, 0.44036697, 0.44954128,
       0.4587156 , 0.46788991, 0.47706422, 0.48623853, 0.49541284,
       0.50458716, 0.51376147, 0.52293578, 0.53211009, 0.5412844 ,
       0.55045872, 0.55963303, 0.56880734, 0.57798165, 0.58715596,
       0.59633028, 0.60550459, 0.6146789 , 0.62385321, 0.63302752,
       0.64220183, 0.65137615, 0.66055046, 0.66972477, 0.67889

In [ ]:
a = np.arange(15)
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [ ]:
a.reshape((3,5))

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [ ]:
a.reshape(3, -1)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [ ]:
a.reshape(-1, 3)

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14]])

# Podsawowe operacje na tablicach

In [ ]:
a = np.array([3, 1, 4, 2])
b = np.array([3, -1, 3, 2])
print(a)
print(b)

[3 1 4 2]
[ 3 -1  3  2]


In [ ]:
np.add(a, b)

array([6, 0, 7, 4])

In [ ]:
np.subtract(a, b)

array([0, 2, 1, 0])

In [ ]:
np.multiply(a, b)

array([ 9, -1, 12,  4])

In [ ]:
a / b

array([ 1.        , -1.        ,  1.33333333,  1.        ])

In [ ]:
a + 3

array([6, 4, 7, 5])

In [ ]:
2 * a

array([6, 2, 8, 4])

In [ ]:
a + 3 * b

array([12, -2, 13,  8])

In [ ]:
x = np.array([[1, 3], [-1, 0]])
y = np.array([[6, 0], [-1, 2]])
print(x, '\n')
print(y)

[[ 1  3]
 [-1  0]] 

[[ 6  0]
 [-1  2]]


In [ ]:
x * y

array([[6, 0],
       [1, 0]])

In [ ]:
np.dot(x, y)

array([[ 3,  6],
       [-6,  0]])

In [ ]:
x.dot(y)

array([[ 3,  6],
       [-6,  0]])

In [ ]:
y.dot(x)

array([[ 6, 18],
       [-3, -3]])

In [ ]:
x @ y

array([[ 3,  6],
       [-6,  0]])

# Generowanie liczb pseudolosowych

In [3]:
np.random.seed(0)

In [4]:
np.random.rand(10)

array([0.5488135 , 0.71518937, 0.60276338, 0.54488318, 0.4236548 ,
       0.64589411, 0.43758721, 0.891773  , 0.96366276, 0.38344152])

In [5]:
np.random.randn(10, 4)

array([[ 0.14404357,  1.45427351,  0.76103773,  0.12167502],
       [ 0.44386323,  0.33367433,  1.49407907, -0.20515826],
       [ 0.3130677 , -0.85409574, -2.55298982,  0.6536186 ],
       [ 0.8644362 , -0.74216502,  2.26975462, -1.45436567],
       [ 0.04575852, -0.18718385,  1.53277921,  1.46935877],
       [ 0.15494743,  0.37816252, -0.88778575, -1.98079647],
       [-0.34791215,  0.15634897,  1.23029068,  1.20237985],
       [-0.38732682, -0.30230275, -1.04855297, -1.42001794],
       [-1.70627019,  1.9507754 , -0.50965218, -0.4380743 ],
       [-1.25279536,  0.77749036, -1.61389785, -0.21274028]])

In [6]:
np.random.rand()

0.15896958364551972

In [7]:
np.random.rand(10)

array([0.11037514, 0.65632959, 0.13818295, 0.19658236, 0.36872517,
       0.82099323, 0.09710128, 0.83794491, 0.09609841, 0.97645947])

In [8]:
np.random.randint(10)

2

In [11]:
np.random.randint(low=10, high=101)

52

In [13]:
np.random.randint(low=10, high=101, size=10)

array([87, 31, 83, 10, 20, 53, 68, 33, 69, 12])

In [14]:
np.random.choice([4, 2, 1, 3, 5])

2

In [15]:
np.random.choice(['pytheon', 'java', 'sql'])

'sql'

In [16]:
data = np.arange(10)
data

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [19]:
np.random.shuffle(data)
data

array([9, 0, 4, 1, 6, 8, 5, 7, 3, 2])

# Podstawowe funkcje

In [21]:
np.exp(1)

2.718281828459045

In [22]:
np.sqrt(9)

3.0

In [24]:
np.all([2, 3, 1])

True

In [25]:
np.any([1, 2, 3])

True

In [26]:
np.any([0, 0, 0])

False

In [27]:
bool(0)

False

In [28]:
bool(1)

True

In [29]:
a = np.random.rand(5)
a

array([0.82894003, 0.00469548, 0.67781654, 0.27000797, 0.73519402])

In [30]:
np.argmax(a)

0

In [31]:
np.argmin(a)

1

In [32]:
np.argsort(a)

array([1, 3, 2, 4, 0])

In [33]:
np.max(a)

0.8289400292173631

In [34]:
np.min(a)

0.004695476192547066

In [35]:
np.mean(a)

0.5033308075041799

In [36]:
np.median(a)

0.6778165367962301

In [37]:
np.std(a)

0.31410314354621877

# Indeksowanie, Wycinanie tablic

In [3]:
a = np.arange(20)
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [39]:
# A[idx], A[start_idx, stop_idx] - jak w range

In [40]:
a[2]

2

In [41]:
a[2:]

array([ 2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18,
       19])

In [42]:
a[[0, 2]]

array([0, 2])

In [43]:
a[10:15]

array([10, 11, 12, 13, 14])

In [46]:
a = a.reshape(4, 5)
a

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [48]:
a[1]  # wytnie cały drugi wiersz (idx 1)

array([5, 6, 7, 8, 9])

In [49]:
a[:, -2]

array([ 3,  8, 13, 18])

In [50]:
a[1, 3]

8

In [52]:
a[1:3, 1:4]  # wytnie kolumny 1 i 2 oraz kolumny 1-3

array([[ 6,  7,  8],
       [11, 12, 13]])

In [ ]:
a[1, 2] = 14
a

# Iteracja po tablicach

In [4]:
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [5]:
for row in a:
  print(row)

0
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19


In [6]:
a.reshape(5,-1)

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19]])

In [9]:
for row in a:
  print(row)

0
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19


# Zmiana rozmiaru tablic

In [10]:
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [11]:
a = a.reshape(5, -1)

In [12]:
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19]])

In [13]:
a.shape

(5, 4)

In [14]:
a.ravel() # wypłaszcza tablicę do jednego wymiaru

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [15]:
a.T # transponowanie macierzy (zamiana wierszy z kolumnami)

array([[ 0,  4,  8, 12, 16],
       [ 1,  5,  9, 13, 17],
       [ 2,  6, 10, 14, 18],
       [ 3,  7, 11, 15, 19]])

# Maski logiczne

In [17]:
a = np.arange(start=-10, stop=10, step=0.5)

In [19]:
a = a.reshape(10, -1)
a

array([[-10. ,  -9.5,  -9. ,  -8.5],
       [ -8. ,  -7.5,  -7. ,  -6.5],
       [ -6. ,  -5.5,  -5. ,  -4.5],
       [ -4. ,  -3.5,  -3. ,  -2.5],
       [ -2. ,  -1.5,  -1. ,  -0.5],
       [  0. ,   0.5,   1. ,   1.5],
       [  2. ,   2.5,   3. ,   3.5],
       [  4. ,   4.5,   5. ,   5.5],
       [  6. ,   6.5,   7. ,   7.5],
       [  8. ,   8.5,   9. ,   9.5]])

In [20]:
a > 0


array([[False, False, False, False],
       [False, False, False, False],
       [False, False, False, False],
       [False, False, False, False],
       [False, False, False, False],
       [False,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True]])

In [21]:
a[a > 0]

array([0.5, 1. , 1.5, 2. , 2.5, 3. , 3.5, 4. , 4.5, 5. , 5.5, 6. , 6.5,
       7. , 7.5, 8. , 8.5, 9. , 9.5])

In [22]:
np.bitwise_and(a > -5, a < 5)

array([[False, False, False, False],
       [False, False, False, False],
       [False, False, False,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True, False, False],
       [False, False, False, False],
       [False, False, False, False]])

In [23]:
a[np.bitwise_and(a > -5, a < 5)] # bitowa koniunkcja (boot)

array([-4.5, -4. , -3.5, -3. , -2.5, -2. , -1.5, -1. , -0.5,  0. ,  0.5,
        1. ,  1.5,  2. ,  2.5,  3. ,  3.5,  4. ,  4.5])

In [25]:
np.bitwise_or(a < -5, a > 5) # bitowa alteratywa(bool)

array([[ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True, False, False],
       [False, False, False, False],
       [False, False, False, False],
       [False, False, False, False],
       [False, False, False, False],
       [False, False, False,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True]])