<a href="https://colab.research.google.com/github/MarcinJanCiesielski/data_science_bootcamp/blob/main/07_Uczenie_glebokie/02_keras.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#Import bibliotek

In [1]:
%tensorflow_version 2.x
import tensorflow as tf
import numpy as np
import pandas as pd
import plotly.express as px
tf.__version__

Colab only includes TensorFlow 2.x; %tensorflow_version has no effect.


'2.9.2'

# Wprowadzenie - pierwszy model

Model skewencyjny to nic innego jak stos warstw

In [2]:
# utworzenie instancji klasy Sequential
from tensorflow.keras.models import Sequential

model = Sequential()
print(model)

In [3]:
from tensorflow.keras.layers import Dense
model.add(Dense(units=4, input_shape=(10,)))

Wyświetlenie podsumowania modelu: metoda summary()

In [4]:
model.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 dense (Dense)               (None, 4)                 44        
                                                                 
Total params: 44
Trainable params: 44
Non-trainable params: 0
_________________________________________________________________


Dodanie kolejnej warstwy

In [5]:
model.add(Dense(units=2))

model.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 dense (Dense)               (None, 4)                 44        
                                                                 
 dense_1 (Dense)             (None, 2)                 10        
                                                                 
Total params: 54
Trainable params: 54
Non-trainable params: 0
_________________________________________________________________


#Funkcja aktywacji

In [6]:
from tensorflow.keras.activations import linear

random_data = np.linspace(start=-3, stop=3, num=300)
data = pd.DataFrame({'data': random_data, 'linear': linear(random_data)})

data.head()

data    linear
0 -3.000000 -3.000000
1 -2.979933 -2.979933
2 -2.959866 -2.959866
3 -2.939799 -2.939799
4 -2.919732 -2.919732

In [7]:
px.line(data, x='data', y='linear', width=500, height=400, range_y=[-3, 3])

In [8]:
from tensorflow.keras.activations import sigmoid

data = pd.DataFrame({'data': random_data, 'sigmoid': sigmoid(random_data)})
data.head()

data   sigmoid
0 -3.000000  0.047426
1 -2.979933  0.048341
2 -2.959866  0.049272
3 -2.939799  0.050221
4 -2.919732  0.051187

In [9]:
px.line(data, x='data', y='sigmoid', width=500, height=400, range_y=[-0.5, 1.5])

In [10]:
from tensorflow.keras.activations import relu

data = pd.DataFrame({'data': random_data, 'relu': relu(random_data)})
data.head()

data  relu
0 -3.000000   0.0
1 -2.979933   0.0
2 -2.959866   0.0
3 -2.939799   0.0
4 -2.919732   0.0

In [11]:
px.line(data, x='data', y='relu', width=500, height=400, range_y=[-0.5, 1.5])

In [12]:
from tensorflow.keras.activations import tanh

data = pd.DataFrame({'data': random_data, 'tanh': tanh(random_data)})
data.head()

data      tanh
0 -3.000000 -0.995055
1 -2.979933 -0.994853
2 -2.959866 -0.994643
3 -2.939799 -0.994424
4 -2.919732 -0.994196

In [13]:
px.line(data, x='data', y='tanh', width=500, height=400, range_y=[-1.5, 1.5])

In [14]:
model = Sequential()
model.add(Dense(units=8, activation='relu', input_shape=(10,)))
model.add(Dense(units=1, activation='sigmoid'))
model.summary()

Model: "sequential_1"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 dense_2 (Dense)             (None, 8)                 88        
                                                                 
 dense_3 (Dense)             (None, 1)                 9         
                                                                 
Total params: 97
Trainable params: 97
Non-trainable params: 0
_________________________________________________________________


#Kompilacja modelu

In [ ]:
# klasyfikacja binarna
model.compile(optimizer='rmsprop',
              loss='binary_crossentropy',
              metrics=['accuracy'])

# klasyfikacja wieloklasowe
model.compile(optimizer='rmsprop',
              loss='categoricla_crossentropy',
              metrics=['accuracy'])

# regresja
model.compile(optimizer='rmsprop',
              loss='mse')

In [ ]:
# model.fit(data, labels, epochs=10, batch_size=32)
# model.fit(data, labels, epochs=10, batch_size=32, validation_split=0.2) 20% wszystkich danych posłuży do walidacji modelu
# model.fit(data, labels, epochs=10, batch_size=32, validation_data=(x_val, y_val))

#Przykład - klasyfikacja binarna

In [15]:
data = np.random.randn(1000, 150)
labels = np.random.randint(2, size=(1000, 1))

print(data.shape)
print(labels.shape)

(1000, 150)
(1000, 1)


In [ ]:
data[:3]

In [ ]:
labels[:10]

In [20]:
model = Sequential()
model.add(Dense(units=32, activation='relu', input_shape=(150,)))
model.add(Dense(units=1, activation='sigmoid')) # w warstwie wyjściowej tylko 1 neuron bo model jest binarny

model.compile(optimizer='rmsprop',
              loss='binary_crossentropy',
              metrics=['accuracy'])

model.fit(data, labels, epochs=20)

Epoch 1/20
32/32 [==============================] - 1s 3ms/step - loss: 0.8499 - accuracy: 0.5160
Epoch 2/20
32/32 [==============================] - 0s 2ms/step - loss: 0.7196 - accuracy: 0.5640
Epoch 3/20
32/32 [==============================] - 0s 2ms/step - loss: 0.6570 - accuracy: 0.6340
Epoch 4/20
32/32 [==============================] - 0s 2ms/step - loss: 0.6128 - accuracy: 0.6650
Epoch 5/20
32/32 [==============================] - 0s 2ms/step - loss: 0.5778 - accuracy: 0.7160
Epoch 6/20
32/32 [==============================] - 0s 2ms/step - loss: 0.5454 - accuracy: 0.7500
Epoch 7/20
32/32 [==============================] - 0s 3ms/step - loss: 0.5173 - accuracy: 0.7780
Epoch 8/20
32/32 [==============================] - 0s 2ms/step - loss: 0.4920 - accuracy: 0.7940
Epoch 9/20
32/32 [==============================] - 0s 2ms/step - loss: 0.4676 - accuracy: 0.8220
Epoch 10/20
32/32 [==============================] - 0s 2ms/step - loss: 0.4456 - accuracy: 0.8300
Epoch 11/20
32/32 [

In [23]:
model = Sequential()
model.add(Dense(units=32, activation='relu', input_shape=(150,)))
model.add(Dense(units=1, activation='sigmoid')) # w warstwie wyjściowej tylko 1 neuron bo model jest binarny

model.compile(optimizer='rmsprop',
              loss='binary_crossentropy',
              metrics=['accuracy'])

model.fit(data, labels, epochs=20, batch_size=64) # dodatni po ilu prubkach ma nastąpić propagacja wsteczna współczynników - szybciej się trenuje, ale ma gorszą dokładność po takiej samej liczbie epoch

Epoch 1/20
16/16 [==============================] - 1s 2ms/step - loss: 0.8548 - accuracy: 0.4780
Epoch 2/20
16/16 [==============================] - 0s 2ms/step - loss: 0.7476 - accuracy: 0.5270
Epoch 3/20
16/16 [==============================] - 0s 3ms/step - loss: 0.6916 - accuracy: 0.5700
Epoch 4/20
16/16 [==============================] - 0s 2ms/step - loss: 0.6522 - accuracy: 0.6110
Epoch 5/20
16/16 [==============================] - 0s 2ms/step - loss: 0.6196 - accuracy: 0.6480
Epoch 6/20
16/16 [==============================] - 0s 2ms/step - loss: 0.5919 - accuracy: 0.6780
Epoch 7/20
16/16 [==============================] - 0s 2ms/step - loss: 0.5669 - accuracy: 0.7150
Epoch 8/20
16/16 [==============================] - 0s 2ms/step - loss: 0.5444 - accuracy: 0.7450
Epoch 9/20
16/16 [==============================] - 0s 2ms/step - loss: 0.5230 - accuracy: 0.7680
Epoch 10/20
16/16 [==============================] - 0s 2ms/step - loss: 0.5038 - accuracy: 0.7860
Epoch 11/20
16/16 [

In [29]:
model = Sequential()
model.add(Dense(units=32, activation='relu', input_shape=(150,)))
model.add(Dense(units=1, activation='sigmoid')) # w warstwie wyjściowej tylko 1 neuron bo model jest binarny

model.compile(optimizer='rmsprop',
              loss='binary_crossentropy',
              metrics=['accuracy'])

model.fit(data, labels, epochs=20, batch_size=32, validation_split=0.2) # 20% danych posłuży do walidacji. model na danych się poprawia, ale na walidacji już nie i to jest najważniejsze

Epoch 1/20
25/25 [==============================] - 1s 9ms/step - loss: 0.8592 - accuracy: 0.5188 - val_loss: 0.8134 - val_accuracy: 0.5000
Epoch 2/20
25/25 [==============================] - 0s 3ms/step - loss: 0.7283 - accuracy: 0.5825 - val_loss: 0.7710 - val_accuracy: 0.5100
Epoch 3/20
25/25 [==============================] - 0s 3ms/step - loss: 0.6596 - accuracy: 0.6200 - val_loss: 0.7491 - val_accuracy: 0.5050
Epoch 4/20
25/25 [==============================] - 0s 4ms/step - loss: 0.6105 - accuracy: 0.6712 - val_loss: 0.7402 - val_accuracy: 0.5250
Epoch 5/20
25/25 [==============================] - 0s 4ms/step - loss: 0.5715 - accuracy: 0.7150 - val_loss: 0.7358 - val_accuracy: 0.5400
Epoch 6/20
25/25 [==============================] - 0s 3ms/step - loss: 0.5378 - accuracy: 0.7462 - val_loss: 0.7383 - val_accuracy: 0.5350
Epoch 7/20
25/25 [==============================] - 0s 4ms/step - loss: 0.5084 - accuracy: 0.7775 - val_loss: 0.7451 - val_accuracy: 0.5150
Epoch 8/20
25/25 [==

In [31]:
model = Sequential()
model.add(Dense(units=32, activation='relu', input_shape=(150,)))
model.add(Dense(1, activation='sigmoid'))

model.compile(optimizer='rmsprop',
              loss='binary_crossentropy',
              metrics=['accuracy'])

history = model.fit(data, labels, epochs=20, batch_size=32, validation_split=0.2, verbose=0) #wyłączy log

In [32]:
metrics = history.history
metrics.keys()

dict_keys(['loss', 'accuracy', 'val_loss', 'val_accuracy'])

In [33]:
model = Sequential()
model.add(Dense(units=32, activation='relu', input_shape=(150,)))
model.add(Dense(1, activation='sigmoid'))

model.compile(optimizer='rmsprop',
              loss='binary_crossentropy',
              metrics=['accuracy'])

history = model.fit(data, labels, epochs=20, batch_size=32, validation_split=0.2, verbose=1)

Epoch 1/20
25/25 [==============================] - 2s 14ms/step - loss: 0.8639 - accuracy: 0.4850 - val_loss: 0.8192 - val_accuracy: 0.5000
Epoch 2/20
25/25 [==============================] - 0s 3ms/step - loss: 0.7331 - accuracy: 0.5512 - val_loss: 0.7826 - val_accuracy: 0.5500
Epoch 3/20
25/25 [==============================] - 0s 3ms/step - loss: 0.6643 - accuracy: 0.6200 - val_loss: 0.7629 - val_accuracy: 0.5200
Epoch 4/20
25/25 [==============================] - 0s 3ms/step - loss: 0.6128 - accuracy: 0.6762 - val_loss: 0.7553 - val_accuracy: 0.5250
Epoch 5/20
25/25 [==============================] - 0s 3ms/step - loss: 0.5712 - accuracy: 0.7175 - val_loss: 0.7515 - val_accuracy: 0.5400
Epoch 6/20
25/25 [==============================] - 0s 3ms/step - loss: 0.5357 - accuracy: 0.7575 - val_loss: 0.7518 - val_accuracy: 0.5250
Epoch 7/20
25/25 [==============================] - 0s 3ms/step - loss: 0.5050 - accuracy: 0.7925 - val_loss: 0.7554 - val_accuracy: 0.5200
Epoch 8/20
25/25 [=

In [36]:
test_data = np.random.randn(5, 150)
test_labels = np.random.randint(2, size=(5,1))

In [37]:
model.predict(test_data)

1/1 [==============================] - 0s 148ms/step


array([[0.11661453],
       [0.1795477 ],
       [0.6631704 ],
       [0.5860386 ],
       [0.884967  ]], dtype=float32)

#Przykład - klasyfikacja wieloklasowa

In [57]:
data = np.random.random((10000, 150))
labels = np.random.randint(10, size=(10000, 1))

In [58]:
print(data.shape)
print(labels.shape)

(10000, 150)
(10000, 1)


In [59]:
labels[:10]

array([[5],
       [7],
       [7],
       [0],
       [6],
       [7],
       [8],
       [6],
       [7],
       [3]])

In [60]:
from tensorflow.keras.utils import to_categorical
labels = to_categorical(labels, num_classes=10)
labels

array([[0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 1., 0., 0.],
       [0., 0., 0., ..., 1., 0., 0.],
       ...,
       [0., 0., 1., ..., 0., 0., 0.],
       [0., 0., 0., ..., 1., 0., 0.],
       [0., 0., 0., ..., 0., 1., 0.]], dtype=float32)

In [49]:
labels[1]

array([[1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 0.]], dtype=float32)

In [61]:
model = Sequential()
model.add(Dense(units=32, activation='relu', input_shape=(150,)))
model.add(Dense(units=10, activation='softmax'))

model.compile(optimizer='rmsprop',
              loss='categorical_crossentropy',
              metrics=['accuracy'])

model.fit(data, labels, batch_size=32, epochs=30, validation_split=0.2)

Epoch 1/30
250/250 [==============================] - 1s 3ms/step - loss: 2.3162 - accuracy: 0.0970 - val_loss: 2.3054 - val_accuracy: 0.0890
Epoch 2/30
250/250 [==============================] - 1s 2ms/step - loss: 2.3037 - accuracy: 0.1007 - val_loss: 2.3038 - val_accuracy: 0.1010
Epoch 3/30
250/250 [==============================] - 1s 2ms/step - loss: 2.3008 - accuracy: 0.1024 - val_loss: 2.3062 - val_accuracy: 0.0990
Epoch 4/30
250/250 [==============================] - 1s 3ms/step - loss: 2.3001 - accuracy: 0.1104 - val_loss: 2.3044 - val_accuracy: 0.1120
Epoch 5/30
250/250 [==============================] - 1s 2ms/step - loss: 2.2969 - accuracy: 0.1125 - val_loss: 2.3098 - val_accuracy: 0.1010
Epoch 6/30
250/250 [==============================] - 1s 2ms/step - loss: 2.2934 - accuracy: 0.1173 - val_loss: 2.3105 - val_accuracy: 0.0970
Epoch 7/30
250/250 [==============================] - 1s 2ms/step - loss: 2.2907 - accuracy: 0.1254 - val_loss: 2.3111 - val_accuracy: 0.0970
Epoch 

In [62]:
test_data = np.random.random((10, 150))

model.predict(test_data)

1/1 [==============================] - 0s 240ms/step


array([[0.16026063, 0.08789529, 0.06772564, 0.06605836, 0.11264176,
        0.10956497, 0.13643986, 0.09861477, 0.09432547, 0.06647334],
       [0.11223444, 0.10313533, 0.10004721, 0.1022664 , 0.07090877,
        0.12837903, 0.14522475, 0.05085544, 0.08970823, 0.09724044],
       [0.15112469, 0.07415983, 0.02146185, 0.01765187, 0.43004727,
        0.09493693, 0.02400144, 0.0690706 , 0.0829253 , 0.0346202 ],
       [0.08223465, 0.09869071, 0.10481367, 0.0974505 , 0.09387915,
        0.09751607, 0.09200161, 0.13013051, 0.11609689, 0.08718618],
       [0.10232042, 0.08934917, 0.0973981 , 0.11624651, 0.07856839,
        0.11163381, 0.08556706, 0.08501888, 0.11762131, 0.11627654],
       [0.08147694, 0.08727682, 0.12784976, 0.11507326, 0.05660928,
        0.09739569, 0.0618455 , 0.1628582 , 0.11633538, 0.09327923],
       [0.15534629, 0.05879512, 0.03684498, 0.1311014 , 0.03078518,
        0.05824841, 0.10602017, 0.14473614, 0.06131837, 0.21680406],
       [0.2609971 , 0.05954429, 0.0160992

In [66]:
predict_classes = np.argmax(model.predict(test_data),axis=1)
predict_classes

1/1 [==============================] - 0s 23ms/step


array([0, 6, 4, 7, 8, 7, 9, 0, 9, 5])

#Przykład - regresja

In [67]:
data = np.random.random((10000, 150))
labels = np.random.random(10000)

In [68]:
labels[:10]

array([0.50963899, 0.80355613, 0.37684933, 0.75038461, 0.07995897,
       0.35553585, 0.49238724, 0.81391703, 0.38265686, 0.85054862])

In [70]:
model = Sequential()
model.add(Dense(units=32, activation='relu', input_shape=(150,)))
model.add(Dense(units=1))

model.compile(optimizer='rmsprop',
              loss='mse')

model.fit(data, labels, epochs=30, batch_size=32, validation_split=0.2)

Epoch 1/30
250/250 [==============================] - 1s 3ms/step - loss: 0.1326 - val_loss: 0.0990
Epoch 2/30
250/250 [==============================] - 0s 2ms/step - loss: 0.0938 - val_loss: 0.0919
Epoch 3/30
250/250 [==============================] - 1s 2ms/step - loss: 0.0878 - val_loss: 0.0884
Epoch 4/30
250/250 [==============================] - 1s 3ms/step - loss: 0.0856 - val_loss: 0.0864
Epoch 5/30
250/250 [==============================] - 1s 4ms/step - loss: 0.0850 - val_loss: 0.0913
Epoch 6/30
250/250 [==============================] - 1s 3ms/step - loss: 0.0845 - val_loss: 0.0882
Epoch 7/30
250/250 [==============================] - 1s 4ms/step - loss: 0.0834 - val_loss: 0.0862
Epoch 8/30
250/250 [==============================] - 1s 3ms/step - loss: 0.0832 - val_loss: 0.0868
Epoch 9/30
250/250 [==============================] - 0s 2ms/step - loss: 0.0827 - val_loss: 0.0924
Epoch 10/30
250/250 [==============================] - 1s 2ms/step - loss: 0.0821 - val_loss: 0.0882

In [71]:
model = Sequential()
model.add(Dense(units=32, activation='relu', input_shape=(150,)))
model.add(Dense(units=1))

model.compile(optimizer='rmsprop',
              loss='mae',
              metrics=['mse'])

model.fit(data, labels, epochs=10, batch_size=32, validation_split=0.2)

Epoch 1/10
250/250 [==============================] - 2s 4ms/step - loss: 0.2718 - mse: 0.1053 - val_loss: 0.2598 - val_mse: 0.0922
Epoch 2/10
250/250 [==============================] - 1s 2ms/step - loss: 0.2539 - mse: 0.0885 - val_loss: 0.2582 - val_mse: 0.0909
Epoch 3/10
250/250 [==============================] - 0s 2ms/step - loss: 0.2512 - mse: 0.0864 - val_loss: 0.2542 - val_mse: 0.0880
Epoch 4/10
250/250 [==============================] - 1s 2ms/step - loss: 0.2492 - mse: 0.0853 - val_loss: 0.2584 - val_mse: 0.0919
Epoch 5/10
250/250 [==============================] - 1s 2ms/step - loss: 0.2489 - mse: 0.0846 - val_loss: 0.2530 - val_mse: 0.0869
Epoch 6/10
250/250 [==============================] - 1s 2ms/step - loss: 0.2477 - mse: 0.0843 - val_loss: 0.2535 - val_mse: 0.0873
Epoch 7/10
250/250 [==============================] - 1s 2ms/step - loss: 0.2465 - mse: 0.0835 - val_loss: 0.2561 - val_mse: 0.0892
Epoch 8/10
250/250 [==============================] - 1s 2ms/step - loss: 0.

In [72]:
test_data = np.random.random((10, 150))

model.predict(test_data)

1/1 [==============================] - 0s 90ms/step


array([[0.49530435],
       [0.51052415],
       [0.65863156],
       [0.55945396],
       [0.67206717],
       [0.5032403 ],
       [0.38565525],
       [0.5082714 ],
       [0.47965464],
       [0.6143812 ]], dtype=float32)